// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqjyfsawplidqouxbhpn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxanlmc2F3cGxpZHFvdXhiaHBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1Nzk0NTYsImV4cCI6MjA2MDE1NTQ1Nn0.Lv6PW8xugPH8aR_fS4Gz5lGuwO_JHhOEppBH_t2bJ6o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);